apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv-volum
  labels:
    type: local
spec:
  storageClassName: manu
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/grafana"