apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-grafana
  labels:
    app: jmeter-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmeter-grafana
  template:
    metadata:
      labels:
        app: jmeter-grafana
    spec:
      initContainers:
      - name: init-chown-data
        image: grafana/grafana:5.2.4
        imagePullPolicy: IfNotPresent
        command: ["chown", "-R", "472:472", "/var/lib/grafana"]      
      containers:
      - name: grafana
        image: grafana/grafana:5.2.4
        imagePullPolicy: IfNotPresent
        ports:
         - containerPort: 3000
           protocol: TCP
        env:
        - name: GF_AUTH_BASIC_ENABLED
          value: "true"
        - name: GF_USERS_ALLOW_ORG_CREATE
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: Admin
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-pv-storage 
      volumes:
      - name: grafana-pv-storage
        persistentVolumeClaim:
          claimName: grafana-pv-claim

